### ISSUE TITLE
bug android 4.3 - always at least 1 mistake

### ISSUE THREAD

**Issue by GoogleCodeExporter** [queler/holokenmod#14]
```
I upgraded to android 4.3 today.  Since that, there is always a mistake 
announced by the check feature. 
If i also can ask for a new setting it will be the ability to disabled sounds 
on marks/pencils. 

Thanks for this nice job.
```

Original issue reported on code.google.com by `Yannickl...@gmail.com` on 14 Dec 2013 at 10:36

**Comment by Ceynou** [comment]
Still always at least 1 mistake, android 10

**Comment by queler** [comment]
i think the original comment was from before I forked, but i have no sounds ever, and i'm not seeing that problem with mistakes.  Got a screenshot?

**Comment by Ceynou** [comment]
![Screenshot_20220622-111104_HoloKenMod](https://user-images.githubusercontent.com/41862916/174991639-3819d8fe-568b-437a-8534-74e3e8c40beb.jpg)
![Screenshot_20220622-111112_HoloKenMod](https://user-images.githubusercontent.com/41862916/174991652-2ca18e39-0840-4c4a-8415-042dd4d8ba77.jpg)

**Comment by queler** [comment]
weird.  Clear data?  I can't replicate this

**Comment by Ceynou** [comment]
I did a forced shutdown, then a wipe data, launched the app, gave the permission to access the storage, started a 4x4 game, checked the mistake and still 1 mistake.
uninstalled, reinstalled from fdroid, same thing.
uninstalled, reinstalled from github, same thing.
