### ISSUE TITLE
I like to have the source of 1.2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [queler/holokenmod#18]
```
The repo only contains source of 1.1.1.

Being a GPL-Program and me being a user, I kindly request the sources of the 
current version 1.2.

I have some time available and like to implement a new feature (first for 
myself, but probably for everyone too).

```

Original issue reported on code.google.com by `ch.hueb...@googlemail.com` on 30 Aug 2014 at 8:06

**Comment by landry314** [comment]
yeah, where is the source? this is why 1.2 isnt in f-droid. the apk for it is available on the website:

https://code.google.com/p/holoken/downloads/detail?name=HoloKen%201.2.apk

but... i want it in the repo!

**Comment by queler** [comment]
look on github under user tortuca
