### ISSUE TITLE
upload source code to f-droid so newest version can be placed in repo

### ISSUE THREAD

**Issue by landry314** [queler/holokenmod#21]
the version in f-droid is behind a version due to lack of a new source code:
https://f-droid.org/repository/browse/?fdid=com.tortuca.holoken

please distribute and upload the source code!

**Comment by landry314** [comment]
https://gitlab.com/fdroid/fdroiddata/blob/master/README.md
https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md

**Comment by queler** [comment]
found the updated version on github user name tortuca, incorporated changed into this fork
