### ISSUE TITLE
Option to count incorrectly removed digits as errors

### ISSUE THREAD

**Issue by dejbug** [queler/holokenmod#29]
Pressing the question-mark will show the current error count. However, only wrongly filled-in cells are counted. Wrongly removed pencil-marks are ignored. An argument could be made that they should be counted too, since they represent assumptions about (im)possible fill-ins. One should be able to know as early as possible that the game will be unsolvable in 20 minutes. Also the undo operation is meaningless without knowing at what point one's initial wrong assumption happened. There is a snowballing effect.

**Comment by queler** [comment]
I think that design is ok.  Pencil is pencil for reason.
